[DEFAULT]
APP_ID = '116680419'
API_KEY = 'sA6kPk7sYYNo1Cl1KRCFRXeT'
SECRET_KEY = 'PehpKiq76EgaMTKmtNVvb2skA8qyVlPm'
X_GEWE_TOKEN= 'dc2c76ec52e547a0ab78655c94c3c785'
# GEWE_APP_ID will be dynamically set in util.py
QIANFAN_API_KEY= 3Y2wi1MvqvNsADGPsWILj6U6
QIANFAN_SECRET_KEY= w4vGplZLzg7b3PmDjMDZk3FpSFAguzw9
BURL = 'http://36.133.97.233:2531/v2/api'